version: '3.8'

services:
  api:
    container_name: holomentor_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - env.properties
    volumes:
      - .:/app