CREATE TYPE user_roles AS ENUM('SUPER_ADMIN', 'ADMIN', 'USER');

ALTER TABLE users ADD COLUMN role user_roles NOT NULL DEFAULT 'USER';
ALTER TABLE users ADD COLUMN is_blacklisted BOOLEAN NOT NULL DEFAULT false;