ALTER TABLE users ADD COLUMN image TEXT;
ALTER TABLE users ADD COLUMN country VARCHAR(255);
ALTER TABLE users ADD COLUMN country_code VARCHAR(255);
ALTER TABLE users ADD COLUMN contact_number VARCHAR(255);